{
    "compatibility_info": {
        "version": "22.00",
        "type": "rendernodegraph"
    },
    "renderNodeGraphName": "",
    "nodes": [
        {
            "typeName": "RenderNodeCreateDefaultCameraGpuImages",
            "nodeName": "RenderNodeCreateDefaultCameraGpuImages",
            "gpuImageDescs": [
                {
                    "name": "output",
                    "shareName": "output",
                    "format": "b10g11r11_ufloat_pack32",
                    "usageFlags": "color_attachment | input_attachment | sampled",
                    "engineCreationFlags": "dynamic_barriers"
                },
                {
                    "name": "depth",
                    "shareName": "depth",
                    "format": "d32_sfloat",
                    "usageFlags": "depth_stencil_attachment | input_attachment | sampled",
                    "memoryPropertyFlags": "device_local | lazily_allocated",
                    "engineCreationFlags": "dynamic_barriers"
                },
                {
                    "name": "color",
                    "shareName": "color",
                    "format": "b10g11r11_ufloat_pack32",
                    "usageFlags": "color_attachment | input_attachment | sampled",
                    "memoryPropertyFlags": "device_local",
                    "engineCreationFlags": "dynamic_barriers"
                },
                {
                    "name": "velocity_normal",
                    "shareName": "velocity_normal",
                    "format": "r16g16b16a16_sfloat",
                    "usageFlags": "color_attachment | input_attachment | sampled",
                    "memoryPropertyFlags": "device_local | lazily_allocated",
                    "engineCreationFlags": "dynamic_barriers"
                },
                {
                    "name": "history",
                    "shareName": "history",
                    "format": "b10g11r11_ufloat_pack32",
                    "usageFlags": "color_attachment | input_attachment | sampled",
                    "memoryPropertyFlags": "device_local",
                    "engineCreationFlags": "dynamic_barriers"
                },
                {
                    "name": "base_color",
                    "shareName": "base_color",
                    "format": "r8g8b8a8_srgb",
                    "usageFlags": "color_attachment | input_attachment | transient_attachment",
                    "memoryPropertyFlags": "device_local | lazily_allocated",
                    "engineCreationFlags": "dynamic_barriers"
                },
                {
                    "name": "material",
                    "shareName": "material",
                    "format": "r8g8b8a8_unorm",
                    "usageFlags": "color_attachment | input_attachment | transient_attachment",
                    "memoryPropertyFlags": "device_local | lazily_allocated",
                    "engineCreationFlags": "dynamic_barriers"
                },
                {
                    "name": "uv",
                    "shareName": "uv",
                    "format": "r16g16_sfloat",
                    "usageFlags": "color_attachment | input_attachment | sampled | storage",
                    "memoryPropertyFlags": "device_local",
                    "engineCreationFlags": "dynamic_barriers"
                }
            ]
        },
        {
            "typeName": "RenderNodeCreateGpuImages",
            "_comment": "changing this nodeName will cause strange issue...",
            "nodeName": "RenderNodeCreateGpuImages",
            "gpuImageDescs": [
                {
                    "name": "lr_texture",
                    "shareName": "lr_texture",
                    "format": "r8g8b8a8_unorm",
                    "width": 512,
                    "height": 512,
                    "usageFlags": "sampled | storage",
                    "memoryPropertyFlags": "device_local",
                    "engineCreationFlags": "dynamic_barriers"
                },
                {
                    "name": "lr_gradient",
                    "shareName": "lr_gradient",
                    "format": "r32g32b32a32_sfloat",
                    "width": 512,
                    "height": 512,
                    "usageFlags": "storage | sampled",
                    "memoryPropertyFlags": "device_local",
                    "engineCreationFlags": "dynamic_barriers"
                },
                {
                    "name": "lr_momentum1",
                    "shareName": "lr_momentum1",
                    "format": "r32g32b32a32_sfloat",
                    "width": 512,
                    "height": 512,
                    "usageFlags": "storage | sampled",
                    "memoryPropertyFlags": "device_local",
                    "engineCreationFlags": "dynamic_barriers"
                },
                {
                    "name": "lr_momentum2",
                    "shareName": "lr_momentum2",
                    "format": "r32g32b32a32_sfloat",
                    "width": 512,
                    "height": 512,
                    "usageFlags": "storage | sampled",
                    "memoryPropertyFlags": "device_local",
                    "engineCreationFlags": "dynamic_barriers"
                },
                {
                    "name": "loss_output",
                    "shareName": "loss_output",
                    "format": "r32_sfloat",
                    "width": 1024,
                    "height": 1024,
                    "usageFlags": "storage | sampled",
                    "memoryPropertyFlags": "device_local",
                    "engineCreationFlags": "dynamic_barriers"
                },
                {
                    "name": "debugOutput",
                    "shareName": "debugOutput",
                    "format": "r32g32b32a32_sfloat",
                    "dependencyImageName": "depth",
                    "dependencyFlags": "size",
                    "dependencySizeScale": 1,
                    "usageFlags": "storage | sampled",
                    "memoryPropertyFlags": "device_local",
                    "engineCreationFlags": "dynamic_barriers"
                },
                {
                    "name": "predicted_base_color",
                    "shareName": "predicted_base_color",
                    "format": "b10g11r11_ufloat_pack32",
                    "dependencyImageName": "depth",
                    "dependencyFlags": "size",
                    "dependencySizeScale": 1,
                    "usageFlags": "color_attachment | storage | sampled",
                    "memoryPropertyFlags": "device_local",
                    "engineCreationFlags": "dynamic_barriers"
                },
                {
                    "name": "testColor",
                    "shareName": "testColor",
                    "format": "b10g11r11_ufloat_pack32",
                    "dependencyImageName": "depth",
                    "dependencyFlags": "size",
                    "dependencySizeScale": 1,
                    "usageFlags": "color_attachment | storage | sampled",
                    "memoryPropertyFlags": "device_local",
                    "engineCreationFlags": "dynamic_barriers"
                }
            ]
        },
        {
            "typeName": "RenderNodeSRDownsampleInit",
            "nodeName": "SR_DOWNSAMPLE_INIT",
            "queue": {
                "type": "graphics",
                "index": 0
            }
        },
        {
            "typeName": "RenderNodeDefaultCameraController",
            "nodeName": "RenderNodeDefaultCameraController"
        },
        {
            "typeName": "RenderNodeDefaultMaterialRenderSlot",
            "nodeName": "CORE3D_RN_CAM_DM_SO_DF",
            "renderDataStore": {
                "dataStoreName": "RenderDataStorePod",
                "typeName": "RenderDataStorePod",
                "configurationName": "CORE3D_POST_PROCESS_CAM"
            },
            "queue": {
                "type": "graphics",
                "index": 0
            },
            "renderSlot": "CORE3D_RS_DM_DF_OPAQUE",
            "renderSlotSortType": "by_material",
            "renderSlotCullType": "view_frustum_cull",
            "nodeFlags": 0,
            "nodeMaterialDiscardFlags": 8192,
            "renderPass": {
                "attachments": [
                    {
                        "loadOp": "clear",
                        "clearDepth": [
                            1.0,
                            0
                        ],
                        "storeOp": "store",
                        "name": "depth"
                    },
                    {
                        "loadOp": "clear",
                        "clearColor": [
                            0.0,
                            0.0,
                            0.0,
                            0.0
                        ],
                        "storeOp": "store",
                        "name": "color"
                    },
                    {
                        "loadOp": "clear",
                        "clearColor": [
                            0.0,
                            0.0,
                            0.0,
                            0.0
                        ],
                        "storeOp": "store",
                        "name": "velocity_normal"
                    },
                    {
                        "loadOp": "clear",
                        "clearColor": [
                            0.0,
                            0.0,
                            0.0,
                            0.0
                        ],
                        "storeOp": "store",
                        "name": "base_color"
                    },
                    {
                        "loadOp": "clear",
                        "clearColor": [
                            0.0,
                            0.0,
                            0.0,
                            0.0
                        ],
                        "storeOp": "store",
                        "name": "material"
                    },
                    {
                        "loadOp": "clear",
                        "clearColor": [
                            0.0,
                            0.0,
                            0.0,
                            0.0
                        ],
                        "storeOp": "store",
                        "name": "uv"
                    },
                    {
                        "loadOp": "clear",
                        "clearColor": [
                            0.0,
                            0.0,
                            0.0,
                            0.0
                        ],
                        "storeOp": "store",
                        "name": "predicted_base_color",
                        "resourceLocation": "from_named_render_node_output",
                        "nodeName": "RenderNodeCreateGpuImages"
                    },
                    {
                        "loadOp": "clear",
                        "clearColor": [
                            0.0,
                            0.0,
                            0.0,
                            0.0
                        ],
                        "storeOp": "store",
                        "name": "testColor",
                        "resourceLocation": "from_named_render_node_output",
                        "nodeName": "RenderNodeCreateGpuImages"
                    }
                ],
                "subpassIndex": 0,
                "subpassCount": 2,
                "subpass": {
                    "depthAttachmentIndex": 0,
                    "colorAttachmentIndices": [
                        1,
                        2,
                        3,
                        4,
                        5
                    ]
                }
            }
        },
        {
            "typeName": "RenderNodeDefaultMaterialDeferredShading",
            "nodeName": "CORE3D_RN_CAM_DM_DS_DF",
            "renderDataStore": {
                "dataStoreName": "RenderDataStorePod",
                "typeName": "RenderDataStorePod",
                "configurationName": "CORE3D_POST_PROCESS_CAM"
            },
            "queue": {
                "type": "graphics",
                "index": 0
            },
            "nodeFlags": 0,
            "shader": "assets://app/shader/core3d_dm_fullscreen_deferred_shading.shader",
            "renderPass": {
                "_comment": "attachments must match the first subpass: same names, count, and order",
                "attachments": [
                    {
                        "name": "depth",
                        "storeOp": "store"
                    },
                    {
                        "name": "color",
                        "storeOp": "store"
                    },
                    {
                        "name": "velocity_normal",
                        "storeOp": "store"
                    },
                    {
                        "name": "base_color",
                        "storeOp": "store"
                    },
                    {
                        "name": "material",
                        "storeOp": "store"
                    },
                    {
                        "name": "uv",
                        "storeOp": "store"
                    },
                    {
                        "name": "predicted_base_color",
                        "storeOp": "store"
                    },
                    {
                        "name": "testColor",
                        "storeOp": "store"
                    }
                ],
                "subpassIndex": 1,
                "subpassCount": 2,
                "subpass": {
                    "colorAttachmentIndices": [
                        1,
                        6,
                        7
                    ],
                    "inputAttachmentIndices": [
                        0,
                        2,
                        3,
                        4,
                        5
                    ]
                }
            },
            "resources": {
                "images": [
                    {
                        "set": 2,
                        "binding": 0,
                        "name": "lr_texture"
                    }
                ],
                "samplers": [
                    {
                        "set": 2,
                        "binding": 1,
                        "name": "CORE_DEFAULT_SAMPLER_LINEAR_MIPMAP_REPEAT"
                    }
                ]
            }
        },
        {
            "typeName": "RenderNodeSRTraining",
            "nodeName": "SR_TRAINING",
            "queue": {
                "type": "compute",
                "index": 0
            },
            "resources": [
                {
                    "type": "texture",
                    "name": "depthBuffer",
                    "binding": 0,
                    "usageName": "depth"
                },
                {
                    "type": "texture",
                    "name": "normalBuffer",
                    "binding": 1,
                    "usageName": "velocity_normal"
                },
                {
                    "type": "texture",
                    "name": "materialBuffer",
                    "binding": 2,
                    "usageName": "material"
                },
                {
                    "type": "texture",
                    "name": "uvBuffer",
                    "binding": 3,
                    "usageName": "uv"
                },
                {
                    "type": "texture",
                    "name": "baseColorBuffer",
                    "binding": 4,
                    "usageName": "base_color"
                },
                {
                    "type": "texture",
                    "name": "lrTexture",
                    "binding": 5,
                    "usageName": "lr_texture"
                },
                {
                    "type": "sampler",
                    "name": "sampler",
                    "binding": 6
                },
                {
                    "type": "texture",
                    "name": "gtImage",
                    "binding": 9,
                    "usageName": "color"
                }
            ],
            "images": [
                {
                    "name": "lrGradient",
                    "binding": 7,
                    "usageName": "lr_gradient"
                },
                {
                    "name": "lossOutput",
                    "binding": 8,
                    "usageName": "loss_output"
                },
                {
                    "name": "lrMomentum1",
                    "binding": 10,
                    "usageName": "lr_momentum1"
                },
                {
                    "name": "lrMomentum2",
                    "binding": 11,
                    "usageName": "lr_momentum2"
                }
            ]
        },
        {
            "typeName": "RenderNodeBackBuffer",
            "nodeName": "RenderNodeBackBuffer",
            "renderDataStore": {
                "dataStoreName": "RenderDataStorePod",
                "typeName": "RenderDataStorePod",
                "configurationName": "CORE3D_POST_PROCESS_CAM"
            },
            "queue": {
                "type": "graphics",
                "index": 0
            },
            "shader": "assets://app/shader/split_screen_display.shader",
            "renderPass": {
                "attachments": [
                    {
                        "loadOp": "dont_care",
                        "storeOp": "store",
                        "name": "CORE_DEFAULT_BACKBUFFER"
                    }
                ],
                "subpass": {
                    "colorAttachmentIndices": 0
                }
            },
            "resources": {
                "images": [
                    {
                        "set": 0,
                        "binding": 1,
                        "name": "debugOutput"
                    },
                    {
                        "set": 0,
                        "binding": 2,
                        "name": "color"
                    },
                    {
                        "set": 0,
                        "binding": 3,
                        "name": "lr_texture"
                    },
                    {
                        "set": 0,
                        "binding": 4,
                        "name": "lr_gradient"
                    }
                ],
                "samplers": [
                    {
                        "set": 0,
                        "binding": 0,
                        "name": "CORE_DEFAULT_SAMPLER_LINEAR_CLAMP"
                    }
                ]
            }
        }
    ]
}