#version 460 core
#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable

layout(set = 0, binding = 0) uniform sampler defaultSampler;
layout(set = 0, binding = 1) uniform texture2D rawAlbedo;
layout(set = 0, binding = 2) uniform texture2D rawNormal;
layout(set = 0, binding = 3) uniform texture2D rawMaterial;
layout(set = 0, binding = 4) uniform texture2D rawEmissive;
layout(set = 0, binding = 5) uniform texture2D rawAO;
layout(set = 0, binding = 6) uniform uMaskUbo {
    uint uMaskFlags;
};
layout(set = 0, binding = 7, rgba32f) uniform image2D lrTexture;

const uint MASK_BASE_COLOR = 1u << 0u;
const uint MASK_NORMAL     = 1u << 1u;
const uint MASK_MATERIAL   = 1u << 2u;
const uint MASK_EMISSIVE   = 1u << 3u;
const uint MASK_AO         = 1u << 4u;

layout(push_constant, std430) uniform uPushConstant {
    ivec2 destSize;
};

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

void main() {
    ivec2 destCoord = ivec2(gl_GlobalInvocationID.xy);
    
    if (destCoord.x >= destSize.x || destCoord.y >= destSize.y) {
        return;
    }

    vec2 uv = (vec2(destCoord) + 0.5) / vec2(destSize);

    vec4 selected = textureLod(sampler2D(rawAlbedo, defaultSampler), uv, 0.0);
    if ((uMaskFlags & MASK_NORMAL) == MASK_NORMAL) {
        selected = textureLod(sampler2D(rawNormal, defaultSampler), uv, 0.0);
    } else if ((uMaskFlags & MASK_MATERIAL) == MASK_MATERIAL) {
        selected = textureLod(sampler2D(rawMaterial, defaultSampler), uv, 0.0);
    } else if ((uMaskFlags & MASK_EMISSIVE) == MASK_EMISSIVE) {
        selected = textureLod(sampler2D(rawEmissive, defaultSampler), uv, 0.0);
    } else if ((uMaskFlags & MASK_AO) == MASK_AO) {
        selected = textureLod(sampler2D(rawAO, defaultSampler), uv, 0.0);
    }

    imageStore(lrTexture, destCoord, selected);
}
