#version 460 core
#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable

layout(set = 0, binding = 0) uniform texture2D uSourceTex;
layout(set = 0, binding = 1) uniform sampler uSampler;
layout(set = 0, binding = 2, rgba8) uniform image2D uDestImage;
layout(set = 0, binding = 3, rgba32f) uniform image2D uLRGradient;

layout(push_constant, std430) uniform uPushConstant {
    vec2 sourceSize;
    vec2 destSize;
};

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

void main() {
    ivec2 destCoord = ivec2(gl_GlobalInvocationID.xy);
    
    if (destCoord.x >= int(destSize.x) || destCoord.y >= int(destSize.y)) {
        return;
    }

    // 只在首次初始化纹理
    if (sourceSize.x < 1.) {
        // 计算在源纹理中的对应位置
        vec2 uv = (vec2(destCoord) + 0.5) / 512; // 有问题，运行的时候destSize=2048，但debug的时候是512

        // 使用双线性采样下采样
        vec4 color = textureLod(sampler2D(uSourceTex, uSampler), uv, 0.0);

        // color = vec4(0.2, 0.2, 0.2, 1.);

        // 写入目标纹理
        imageStore(uDestImage, destCoord, color);
    }

    // 每次在使用uLRGradient前清空
    imageStore(uLRGradient, destCoord, vec4(0.0));
}
